### ISSUE TITLE
Package Manager absorbs the error stack trace from packages, making it difficult to debug

### ISSUE THREAD

**Issue by pmasrani** [vmware/liota#135] opened 2017-06-23 10:41 UTC
Package Manager absorbs the error stack trace in most of the cases. For example, https://github.com/vmware/liota/blob/master/liota/core/package_manager.py#L705

Instead of Log.error, Log.exception should be used in such places, to print the exception along with the stacktrace.

**Comment by bfrggit** [comment] 2017-06-30 18:46
Agreed.

BTW, I got `ERROR [PackageThread] liota.core.package_manager._package_load(705) - Exception in initialization: 'RegisteredEntity' object has no attribute 'name'` when loading `examples/graphite_edge_system_stats.py`. Not sure where it is from.

**Comment by KohliDev** [comment] 2017-06-30 20:11
The issue is fixed in my next pull request. Remove the double registration happening at
 ```
examples/graphite_edge_system_stats.py

Line no 73        reg_edge_system = graphite.register(edge_system)
```

I`m not sure in which pull request this got merged.

**Comment by pmasrani** [comment] 2017-07-03 07:00
I had raised a separate issue for the same: https://github.com/vmware/liota/issues/122

**Comment by bfrggit** [comment] 2017-08-08 00:38
This has been changed in pull request https://github.com/vmware/liota/pull/141

**Closed** 2017-10-04 13:35 UTC
