### ISSUE TITLE
Pip puts data files in the wrong place in the directory hierarchy

### ISSUE THREAD

**Issue by GregBollella** [vmware/liota#4] opened 2016-05-26 19:27 UTC
Installing liota (0.1) on Snappy Ubuntu and Wind River IDP we noticed that the data files (in conf and example) directories are going to the wrong place in the hierarchy. They are supposed to go in /etc/liota but end up in /usr/lib/python2.7/site-packages/etc/...

**Comment by KohliRocks** [comment] 2016-06-09 13:05
The issue is fixed in the following commit 53efc89fcef20f0b2266cc7e7722fdf79deb955a

The issue was occurring due to the wrong path getting generated during install process by pip. The path is generated at runtime for “data_files” as we upload the source distribution on PyPI website. It is fixed by first getting the root path using “os.path.abspath(os.sep)” and then creating the “/etc/liota” directory with its reference. It worked fine in all the above systems tested.

**Closed by KohliRocks** 2016-06-09 13:05 UTC
